import { defaultTheme, Theme } from './common/theming';

export const themes: Theme[] = [
  { ...defaultTheme, title: 'Yana Original' },
  {
    title: 'Ice Cave',
    primaryColor: '#7bb2ec',
    sidebarColor: '#d6dde4',
    sidebarTextColor: '#3a4149',
    sidebarHoverColor: '#9fb0c2',
    topBarColor: '#2370b9',
  },
  {
    title: 'Crunchy Carrot',
    primaryColor: '#FF8334',
    sidebarColor: '#EED6C4',
    sidebarTextColor: '#66370D',
    sidebarHoverColor: '#DFB99D',
    topBarColor: '#B95D23',
  },
  {
    title: 'Luxurious Apartment',
    primaryColor: '#E2C37A',
    sidebarColor: '#E7E7EB',
    sidebarTextColor: '#1A1D20',
    sidebarHoverColor: '#DDD9C9',
    topBarColor: '#01080E',
  },
  {
    title: 'Banana Tree',
    primaryColor: '#FD8504',
    sidebarColor: '#FFEB84',
    sidebarTextColor: '#745B28',
    sidebarHoverColor: '#F1CB42',
    topBarColor: '#FFC806',
  },
  {
    title: 'Sweet Tooth',
    primaryColor: '#F8D1D0',
    sidebarColor: '#FFD6EF',
    sidebarTextColor: '#6D304C',
    sidebarHoverColor: '#FFBDDB',
    topBarColor: '#EEA4C6',
  },
  {
    title: 'Spooky Halloween',
    primaryColor: '#F3850C',
    sidebarColor: '#523C26',
    sidebarTextColor: '#AF926D',
    sidebarHoverColor: '#2A2018',
    topBarColor: '#30261C',
  },
  {
    title: 'Touch of Christmas',
    primaryColor: '#BB2528',
    sidebarColor: '#165B33',
    sidebarTextColor: '#38C978',
    sidebarHoverColor: '#126937',
    topBarColor: '#0A4121',
  },
  {
    title: 'The Greener Side',
    primaryColor: '#42C337',
    sidebarColor: '#2C502C',
    sidebarTextColor: '#8ABE8C',
    sidebarHoverColor: '#335F34',
    topBarColor: '#294828',
  },
  {
    title: 'Oriental Basar',
    primaryColor: '#9E49E7',
    sidebarColor: '#412C50',
    sidebarTextColor: '#A985BD',
    sidebarHoverColor: '#4E3261',
    topBarColor: '#692A81',
  },
  {
    title: 'Crimson Forest',
    primaryColor: '#DD5640',
    sidebarColor: '#502C2C',
    sidebarTextColor: '#B98B8B',
    sidebarHoverColor: '#613636',
    topBarColor: '#482928',
  },
  {
    title: 'Nord Light',
    primaryColor: '#88C0D0',
    sidebarColor: '#E5E9F0',
    sidebarTextColor: '#4C566A',
    sidebarHoverColor: '#D8DEE9',
    topBarColor: '#2E3440',
  },
  {
    title: 'Nord Dark',
    primaryColor: '#88C0D0',
    sidebarColor: '#3B4252',
    sidebarTextColor: '#B2BACA',
    sidebarHoverColor: '#5E81AC',
    topBarColor: '#2E3440',
  },
];
