name: CI

on:
  push:
  workflow_dispatch:

env:
  YARN_GPG: no 
  GH_TOKEN: ${{ secrets.GH_SECRET }}
  DEBUG: electron-builder

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v3
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Dependencies
        run: yarn install --network-timeout 1000000000
      - name: Build
        run: yarn build --publish=never

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v3
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Dependencies
        run: yarn install --network-timeout 1000000000
      - name: Build
        run: yarn build --publish=never

  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v3
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Dependencies
        run: yarn install --network-timeout 1000000000
      - name: Build
        run: yarn build --publish=never
